name: build and deploy hosting

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@master
      - name: setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: Transpile TypeScript (npx tsc)
        run: npx tsc
      - name: deploy functions to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: smart-house-dash
